{{- include "photoframe.validate" . -}}
{{- $needAdmin := and .Values.admin.password (not .Values.admin.existingSecret) -}}
{{- $needDb := and (eq .Values.database.type "postgres") (not .Values.database.postgres.existingSecret) -}}
{{- if or $needAdmin $needDb }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photoframe.secretName" . }}
  labels: {{- include "photoframe.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $needAdmin }}
  admin-password: {{ .Values.admin.password | quote }}
  {{- end }}
  {{- if $needDb }}
  database-url: {{ .Values.database.postgres.url | quote }}
  {{- end }}
{{- end }}
