apiVersion: v1
kind: Service
metadata:
  name: {{ include "photoframe.name" . }}
  labels: {{- include "photoframe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
  selector: {{- include "photoframe.selector" (dict "root" . "component" "web") | nindent 4 }}
